In [6]:
import pandas as pd

## Load Raw Data To System

In [9]:
# Data loaded to a variable
sourceData = pd.read_excel(r'C:\Users\hp\Desktop\ML & AL Program Upgrad\Source Files\EDA_Data_Sourcing.xlsx',header=1)

In [8]:
sourceData.head(10)

,Application ID,No of times 90 DPD or worse in last 6 months,No of times 60 DPD or worse in last 6 months,No of times 30 DPD or worse in last 6 months,No of times 90 DPD or worse in last 12 months,No of times 60 DPD or worse in last 12 months,No of times 30 DPD or worse in last 12 months,Avgas CC Utilization in last 12 months,No of trades opened in last 6 months,No of trades opened in last 12 months,No of PL trades opened in last 6 months,No of PL trades opened in last 12 months,No of Inquiries in last 6 months (excluding home & auto loans),No of Inquiries in last 12 months (excluding home & auto loans),Presence of open home loan,Outstanding Balance,Total No of Trades,Presence of open auto loan,Performance Tag
0,954457215,0,0,0,0,0,0,4,1,2,0,0,0,0,1,2999395,4,0,0
1,432830445,0,0,0,0,0,0,3,1,2,0,0,0,0,0,3078,5,0,0
2,941387308,0,0,0,0,0,0,7,0,0,0,0,0,0,1,3004972,2,0,0
3,392161677,0,0,0,0,0,0,11,1,1,0,0,0,0,1,3355373,4,1,0
4,182011211,0,0,0,0,0,0,12,0,1,0,0,0,0,1,3014283,4,0,0
5,312196805,0,0,0,0,0,0,10,0,0,0,0,0,0,0,2569,1,0,0
6,532217204,0,0,0,0,0,0,11,0,1,0,0,0,0,1,3005535,4,0,0
7,74788849,0,0,0,0,0,0,13,1,1,0,0,0,0,1,3004790,3,0,0
8,782743811,0,0,0,0,0,1,9,0,0,0,0,0,0,1,3007428,2,0,0
9,96964957,0,0,0,0,0,0,6,1,1,0,0,0,0,0,170860,1,1,0